services:
  - type: web
    name: pronos-judo-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://pronosAdmin:d1kBl3cR9I8UHZ0y@cluster0.a76ee.mongodb.net/pronos-judo?retryWrites=true&w=majority&appName=Cluster0"
